version: 0.1.{build}
image: Ubuntu
configuration: Release
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: 9PiArQv46K2qlHCfvnHLGaN0VZiICorgLS9DUTobHxYARAtpSzJW8FBMi6niylnL
  skip_symbols: true