version: 1.0.{build}
image: Ubuntu
configuration: Release
environment:
  ssl_cert_dir: /dev/null
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: 9PiArQv46K2qlHCfvnHLGaN0VZiICorgLS9DUTobHxYARAtpSzJW8FBMi6niylnL