version: "3"
services:
  hugo-dev:
    image: hugo-dev
    network_mode: host
    build:
      context: ..
      dockerfile: dev.Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    user: ${USERNAME}
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"  
