version: "3"
services:
  ${NAME}-${ID}-base:
    image: ${NAME}-${ID}-base
    build:
      context: ..
      dockerfile: ${DOCKERFILE}
  ${NAME}-${ID}-devcontainer:
    depends_on: [ "${NAME}-${ID}-base" ]
    image: ${NAME}-${ID}-devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/${DEV_DOCKERFILE}
      args:
        NAME: ${NAME}
        ID: ${ID}
        USERNAME: ${_USERNAME}
        USER_UID: ${_USER_UID:-1000}
        USER_GID: ${_USER_GID:-1000}
    user: ${_USERNAME}
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"  
