name: Release
on:
  push:
    branches:
      - master
    tags:
      - "v*"
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2